title: Joonas Nuutinen
description: I am a full-stack software developer specialised in sustainable development.
author:
  name: Joonas Nuutinen
  email: joonas@nuutinen.codes,
  url: https://nuutinen.codes
