title: Joonas Nuutinen
description: I am a full-stack software developer specialised in sustainable development.
author:
  name: Joonas Nuutinen
  email: joonas@joonasnuutinen.com,
  url: https://joonasnuutinen.com
